#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

killall picom &>/dev/null 
picom &

killall polybar &>/dev/null
polybar aboba &

pkill -f ~/Pictures/feh_changer.sh
~/Pictures/feh_changer.sh ~/Pictures/desktop/ 600 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a org.otter-launcher focus=on state=floating borderless=true rectangle=900x300+970+87

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
